### PR TITLE
react-todo

### PR DESCRIPTION
**Pull request by braincee**

### CODE REVIEW

**Review by ndayishimiyeeric — APPROVED** [review]
**STATUS: APPROVED 🎉✔🍾**
Hello @braincee  👋
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestion:

- Kindly fix the live demo link because it reads back to your repo.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Review by MaganaAsiati — CHANGES_REQUESTED** [review]
Hi @braincee, 👋  

Good job so far!

There are some issues that you still need to work on to go to the next step but you are almost there!

giphy


 ## Highlights 👏 

- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

 ## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions

- [ ]  kindly add the demo for accessibility of your project so that everyone can have easy access to your project

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! 🤓 

✅  Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**Comment by MaganaAsiati** [comment]
- [ ] the design looks good but for the best practice it is better  to use the display flex to arrange items in the navigation bar so that it will look good 
Screenshot from 2022-06-03 23-24-30

**Comment by MaganaAsiati** [comment]
- [ ] kindly implement the button which adds the task and removes the tasks from the to-do list so it will be easy to plan the tasks 
 what you are supposed to do and if you finish doing it you can remove 
- [ ] kindly add the demo for accessibility of your project so that everyone can have easy access to your project

**Comment by braincee** [comment]
Thanks very much @MaganaAsiati @ndayishimiyeeric 
Note: I have made changes as required by @MaganaAsiati to a different branch `add-basic-changes`

thank-you

**Pull request merged**
